[tool.poetry]
name = "nephelaiio.kind"
version = "0.1.0"
description = ""
authors = ["nephelaiio"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
tox = "^3.25.0"
docker = "^6.0.0"
molecule = "^3.6.1"
docker-compose = "^1.29.2"
yamllint = "^1.27.1"
ansible-lint = "~5"
ansible = "^6.1.0"
MarkupSafe = "2.0.1"
pytest = "^7.1.2"
netaddr = "^0.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
