---
- name: check desired cluster status
  ansible.builtin.fail:
    msg: "kind_cluster_state must be one of [{{ kind_valid_states | map('map_format', \"'%s'\") | join(', ') }}]"
  vars:
    kind_valid_states:
      - present
      - absent
  when: kind_cluster_state not in kind_valid_states

- name: check cluster network format
  ansible.builtin.fail:
    msg: "kind_network_addr must be in network/prefix format"
  when: not (kind_network_addr | ansible.utils.ipaddr('network/prefix'))

- name: check cluster network prefix length
  ansible.builtin.fail:
    msg: "kind_network_addr prefix must be /24 or larger"
  when: kind_network_addr | ansible.utils.ipaddr('prefix') | int > 24

- name: create tempdir
  ansible.builtin.tempfile:
    state: directory
    prefix: kind
  register: kind_tmpdir
  changed_when: false

- name: set default kind binary path
  ansible.builtin.set_fact:
    _kind_bin: "{{ kind_tmpdir.path }}/kind"

- name: manage kind cluster
  block:

    - name: check local kind binary
      ansible.builtin.shell: which kind
      register: kind_bin_query
      changed_when: false
      ignore_errors: true

    - name: override kind binary path
      ansible.builtin.set_fact:
        _kind_bin: "{{ kind_bin_query.stdout }}"
      when: not kind_release_download and kind_bin_query is succeeded

    - name: download kind binary
      when: kind_release_download or kind_bin_query is not succeeded
      block:

        - name: set kind release to latest tag
          when: kind_release_tag == 'latest' or kind_release_tag | length == 0
          block:

            - name: query kind releases
              ansible.builtin.uri:
                url: "https://api.github.com/repos/kubernetes-sigs/kind/releases/{{ kind_release_tag }}"
              register: kind_release_query

            - name: set kind release target
              ansible.builtin.set_fact:
                kind_release_tag: "{{ kind_release_query.json.tag_name }}"

        - name: set kind release to requested tag
          ansible.builtin.set_fact:
            kind_release: "{{ kind_release_tag }}"

        - name: debug kind image release
          ansible.builtin.debug:
            msg: "Using kind release '{{ kind_release_tag }}', image 'kindest/node:{{ kind_image_tag }}'"

        - name: stat kind executable
          ansible.builtin.stat:
            path: "{{ _kind_bin }}"
          register: kind_bin_file

        - name: download kind executable
          ansible.builtin.get_url:
            url: "https://kind.sigs.k8s.io/dl/{{ kind_release }}/kind-{{ kind_release_family }}-{{ kind_release_architecture }}"
            dest: "{{ _kind_bin }}"
            mode: 0777
          when: not (kind_bin_file.stat.exists | bool)
          changed_when: false

    - name: copy kind executable
      when: kind_bin is defined
      block:

        - name: copy kind executable to requested location
          ansible.builtin.copy:
            src: "{{ _kind_bin }}"
            dest: "{{ kind_bin }}"
            mode: 0755

        - name: debug kind bin release
          ansible.builtin.debug:
            msg: "Using kind binary at path '{{ kind_bin }}'"

    - name: create kind proxies
      when: kind_cluster_state != 'absent'
      block:

        - name: create docker kind network
          community.docker.docker_network:
            name: "{{ kind_network_name }}"
            ipam_config:
              - subnet: "{{ _supernet }}"
                gateway: "{{ _subnet | ipaddr(1) | ipaddr('address') }}"
                iprange: "{{ _subnet }}"
          vars:
            _supernet: "{{ kind_network_addr }}"
            _subnet: "{{ _supernet | ansible.utils.ipsubnet(24, 0) }}"

        - name: query private registry container info
          community.docker.docker_container_info:
            name: "{{ kind_registry_container }}"
          register: kind_registry_query
          changed_when: false

        - name: deploy docker private registry
          ansible.builtin.command: >
            docker run --name {{ kind_registry_container }} --net {{ kind_network_name }} --net-alias {{ kind_registry_hostname }} -d -p {{ kind_registry_port }}:5000 registry:2
          when:
            - kind_registry_deploy | bool
            - not kind_registry_query.exists

        - name: query proxy container info
          community.docker.docker_container_info:
            name: "{{ kind_proxy_container }}"
          register: kind_proxy_query
          changed_when: false

        - name: deploy docker registry proxy
          ansible.builtin.command: >
            docker run --name {{ kind_proxy_container }} --net {{ kind_network_name }} --net-alias {{ kind_proxy_hostname }} -d registry:2
          when:
            - kind_proxy_deploy | bool
            - not kind_proxy_query.exists

    - name: destroy kind proxies
      when: kind_cluster_state == 'absent'
      block:

        - name: destroy docker private registry
          community.docker.docker_container:
            state: absent
            name: '{{ kind_registry_container }}'
          when: kind_registry_cleanup | bool

        - name: destroy docker registry proxy
          community.docker.docker_container:
            state: absent
            name: '{{ kind_proxy_container }}'
          when: kind_proxy_cleanup | bool

    - name: list kind clusters
      ansible.builtin.command: >-
        {{ _kind_bin }} get clusters -q
      register: kind_cluster_query
      changed_when: false

    - name: set cluster config file metadata
      ansible.builtin.set_fact:
        kind_config_path: "{{ kind_tmpdir.path }}/config.yaml"
        kind_config_content: |
          kind: Cluster

          apiVersion: kind.x-k8s.io/v1alpha4

          {% if (kind_nodes > 1) -%}
          nodes:
            - role: control-plane
            {% for i in range(1, kind_nodes) -%}
            - role: worker
            {% endfor -%}
          {%- endif -%}
          {%- if ((kind_registry_deploy | bool) or (kind_proxy_deploy | bool)) %}

          containerdConfigPatches:
          - |-
          {% endif -%}
          {%- if (kind_registry_deploy | bool) %}
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ kind_registry_hostname }}:{{ kind_registry_port }}"]
              endpoint = ["http://{{ kind_registry_hostname }}:5000"]
          {% endif -%}
          {%- if (kind_proxy_deploy | bool) %}
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
              endpoint = ["http://{{ kind_proxy_hostname }}:5000"]
          {% endif -%}

    - name: create cluster configuration file
      ansible.builtin.copy:
        dest: "{{ kind_config_path }}"
        content: "{{ kind_config_content }}"
        mode: 0640
      changed_when: false

    - name: deploy kind cluster
      ansible.builtin.shell: >-
        {{ _kind_bin }} create cluster {{ args_name }} {{ args_kubeconfig }} {{ args_image_option }} {{ args_config }}
      vars:
        args_name: "--name {{ kind_cluster_name }}"
        args_kubeconfig: "--kubeconfig {{ kind_kubeconfig }}"
        args_image: "--image kindest/node:{{ kind_image_tag }}"
        args_image_option: "{{ args_image if kind_image_tag != 'latest' else '' }}"
        args_config: "--config {{ kind_config_path }}"
      when:
        - kind_cluster_state != 'absent'
        - kind_cluster_name not in kind_cluster_query.stdout_lines

    - name: destroy kind cluster
      ansible.builtin.shell: >-
        {{ _kind_bin }} delete cluster --name {{ kind_cluster_name }}
      when:
        - kind_cluster_state == 'absent'
        - kind_cluster_name in kind_cluster_query.stdout_lines

  always:

    - name: destroy tempdir
      ansible.builtin.file:
        state: absent
        path: "{{ kind_tmpdir.path }}"
      changed_when: false
