---
- name: check desired cluster status
  ansible.builtin.fail:
    msg: "kind_cluster_state must be one of [{{ kind_valid_states | map('map_format', \"'%s'\") | join(', ') }}]"
  vars:
    kind_valid_states:
      - present
      - absent
  when: kind_cluster_state not in kind_valid_states

- name: check cluster network format
  ansible.builtin.fail:
    msg: "kind_network_addr must be in network/prefix format"
  when: not (kind_network_addr | ansible.utils.ipaddr('network/prefix'))

- name: check cluster network prefix length
  ansible.builtin.fail:
    msg: "kind_network_addr prefix must be /24 or larger"
  when: kind_network_addr | ansible.utils.ipaddr('prefix') | int > 24

- name: create tempdir
  ansible.builtin.tempfile:
    state: directory
    prefix: kind
  register: kind_tmpdir
  changed_when: false

- name: set kind deployment target
  ansible.builtin.set_fact:
    _kind_bin: "{{ kind_tmpdir.path }}/kind"

- block:

    - name: set kind release to latest tag
      block:

        - name: query kind releases
          ansible.builtin.uri:
            url: "https://api.github.com/repos/kubernetes-sigs/kind/releases/{{ kind_release_tag }}"
          register: kind_release_query

        - name: set kind release target
          ansible.builtin.set_fact:
            kind_release_tag: "{{ kind_release_query.json.tag_name }}"

      when: kind_release_tag == 'latest' or kind_release_tag | length == 0

    - name: set kind release to requested tag
      ansible.builtin.set_fact:
        kind_release: "{{ kind_release_tag }}"

    - name: debug kind image release
      ansible.builtin.debug:
        msg: "Using kind release '{{ kind_release_tag }}', image 'kindest/node:{{ kind_image_tag }}'"

    - name: stat kind executable
      ansible.builtin.stat:
        path: "{{ _kind_bin }}"
      register: kind_bin_file

    - block:

        - name: download kind executable
          ansible.builtin.get_url:
            url: "https://kind.sigs.k8s.io/dl/{{ kind_release }}/kind-linux-amd64"
            dest: "{{ _kind_bin }}"
            mode: 0755
          when: not (kind_bin_file.stat.exists | bool)
          changed_when: false

      rescue:

        - name: check local kind binary
          ansible.builtin.shell: which kind
          register: kind_bin_query
          changed_when: false

        - name: override local kind binary
          ansible.builtin.set_fact:
            _kind_bin: "{{ kind_bin_query.stdout }}"

    - block:

        - name: copy kind executable to requested location
          ansible.builtin.copy:
            src: "{{ _kind_bin }}"
            dest: "{{ kind_bin }}"
            mode: 0755

        - name: debug kind bin release
          ansible.builtin.debug:
            msg: "Using kind binary release '{{ kind_release_tag }}' at path '{{ kind_bin }}'"

      when: kind_bin is defined

    - block:

        - name: create docker kind network
          community.docker.docker_network:
            name: "{{ kind_network_name }}"
            ipam_config:
              - subnet: "{{ _supernet }}"
                gateway: "{{ _subnet | ipaddr(1) | ipaddr('address') }}"
                iprange: "{{ _subnet }}"
          vars:
            _supernet: "{{ kind_network_addr }}"
            _subnet: "{{ _supernet | ansible.utils.ipsubnet(24, 1) }}"

        - name: deploy docker private registry
          community.docker.docker_container:
            state: started
            name: '{{ kind_registry_container }}'
            image: registry:2
            container_default_behavior: no_defaults
            published_ports:
              - "{{ kind_registry_port }}:{{ kind_registry_port }}"
            restart_policy: unless-stopped
            env:
              REGISTRY_HTTP_HOST: "http://{{ kind_registry_hostname }}:5000"
            network_mode: "{{ kind_network_name }}"
            networks:
              - name: "{{ kind_network_name }}"
                aliases:
                  - "{{ kind_registry_hostname }}"

        - name: deploy docker registry proxy
          community.docker.docker_container:
            state: started
            name: '{{ kind_proxy_container }}'
            image: registry:2
            container_default_behavior: no_defaults
            restart_policy: unless-stopped
            env:
              REGISTRY_HTTP_HOST: "http://{{ kind_proxy_hostname }}:5000"
            network_mode: "{{ kind_network_name }}"
            networks:
              - name: "{{ kind_network_name }}"
                aliases:
                  - "{{ kind_proxy_hostname }}"

      when: kind_cluster_state != 'absent'

    - block:

        - name: deploy docker private registry
          community.docker.docker_container:
            state: absent
            name: '{{ kind_registry_container }}'
          when: kind_registry_cleanup | bool

        - name: deploy docker registry proxy
          community.docker.docker_container:
            state: absent
            name: '{{ kind_proxy_container }}'
          when: kind_proxy_cleanup | bool

      when: kind_cluster_state == 'absent'

    - name: list kind clusters
      ansible.builtin.command: >-
        {{ _kind_bin }} get clusters -q
      register: kind_cluster_query
      changed_when: false

    - name: set cluster config file metadata
      ansible.builtin.set_fact:
        kind_config_path: "{{ kind_tmpdir.path }}/config.yaml"
        kind_config_content: |
          kind: Cluster

          apiVersion: kind.x-k8s.io/v1alpha4

          {% if (kind_nodes > 1) -%}
          nodes:
            - role: control-plane
            {% for i in range(1, kind_nodes) -%}
            - role: worker
            {% endfor -%}
          {%- endif -%}
          {%- if ((kind_registry_deploy | bool) or (kind_proxy_deploy | bool)) %}

          containerdConfigPatches:
          - |-
          {% endif -%}
          {%- if (kind_proxy_deploy | bool) %}
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ kind_registry_hostname }}:5000"]
              endpoint = ["http://{{ kind_registry_hostname }}:5000"]
          {% endif -%}
          {%- if (kind_registry_deploy | bool) %}
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
              endpoint = ["http://{{ kind_proxy_hostname }}:5000"]
          {% endif -%}

    - name: create cluster configuration file
      ansible.builtin.copy:
        dest: "{{ kind_config_path }}"
        content: "{{ kind_config_content }}"
      changed_when: false

    - name: deploy kind cluster
      ansible.builtin.shell: >-
        {{ _kind_bin }} create cluster {{ args_name }} {{ args_kubeconfig }} {{ args_image_option }} {{ args_config }}
      vars:
        args_name: "--name {{ kind_cluster_name }}"
        args_kubeconfig: "--kubeconfig {{ kind_kubeconfig }}"
        args_image: "--image kindest/node:{{ kind_image_tag }}"
        args_image_option: "{{ args_image if kind_image_tag != 'latest' else '' }}"
        args_config: "--config {{ kind_config_path }}"
      when:
        - kind_cluster_state != 'absent'
        - kind_cluster_name not in kind_cluster_query.stdout_lines

    - name: destroy kind cluster
      ansible.builtin.shell: >-
        {{ _kind_bin }} delete cluster --name {{ kind_cluster_name }}
      when:
        - kind_cluster_state == 'absent'
        - kind_cluster_name in kind_cluster_query.stdout_lines

  always:

    - name: destroy tempdir
      ansible.builtin.file:
        state: absent
        path: "{{ kind_tmpdir.path }}"
      changed_when: false
