---
- name: cleanup

  hosts: localhost

  gather_facts: false

  vars_files:

    - vars/registry.yml

  roles:

    - nephelaiio.plugins

  tasks:

    - name: query kind network info
      community.docker.docker_network_info:
        name: "{{ registry_docker_net }}"
      register: docker_net_kind

    - name: destroy test docker registry
      community.docker.docker_compose:
        state: absent
        project_name: "{{ registry_compose_name }}"
        definition: "{{ registry_compose_def | from_yaml }}"
        remove_orphans: true
      when: docker_net_kind.exists
