---
- name: Destroy
  hosts: localhost
  gather_facts: true
  vars:
    kind_cluster_state: absent
    kind_registry_container: "{{ kind_cluster_name }}-registry"
    kind_proxy_container: "{{ kind_cluster_name }}-proxy"
  roles:
    - nephelaiio.plugins
    - nephelaiio.kind
  tasks:
    - name: Query local registry container info
      community.docker.docker_container_info:
        name: "{{ kind_registry_container }}"
      register: registry_container

    - name: Verify registry container cleanup
      ansible.builtin.assert:
        that: not (registry_container.exists | bool)
        fail_msg: "container {{ kind_registry_container }} was not cleaned up properly"
      when: kind_registry_cleanup | bool

    - name: Query registry proxy container info
      community.docker.docker_container_info:
        name: "{{ kind_proxy_container }}"
      register: proxy_container

    - name: Verify proxy container status
      ansible.builtin.assert:
        that: not (proxy_container.exists | bool)
        msg: "container {{ kind_proxy_container }} was not cleaned up properly"
      when: kind_proxy_cleanup | bool
