---
- name: prepare

  hosts: localhost

  gather_facts: false

  vars_files:

    - vars/registry.yml

  roles:

    - nephelaiio.plugins

  tasks:

    - name: deploy test docker registry
      community.docker.docker_compose:
        state: present
        project_name: "{{ registry_compose_name }}"
        definition: "{{ registry_compose_def | from_yaml }}"
        remove_orphans: true
