---
- name: Verify
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print debug info
      ansible.builtin.debug:
        msg: "using kubeconfig at {{ kind_kubeconfig }}"

    - name: Set default Kind binary path
      ansible.builtin.set_fact:
        _kind_bin: "{{ _tmpdir }}/kind"

    - name: Check local Kind binary
      ansible.builtin.shell: which kind
      register: kind_bin_query
      changed_when: false

    - name: Override Kind binary path
      ansible.builtin.set_fact:
        _kind_bin: "{{ kind_bin_query.stdout }}"
      when: kind_bin_query is succeeded

    - name: Download Kind binary
      when: kind_bin_query is not succeeded
      block:
        - name: Set Kind release to latest tag
          when: kind_release_tag == 'latest' or kind_release_tag | length == 0
          block:
            - name: Query Kind releases
              ansible.builtin.uri:
                url: "https://api.github.com/repos/kubernetes-sigs/kind/releases/{{ kind_release_tag }}"
              register: kind_release_query

            - name: Set Kind release target
              ansible.builtin.set_fact:
                kind_release_tag: "{{ kind_release_query.json.tag_name }}"

        - name: Set Kind release to requested tag
          ansible.builtin.set_fact:
            kind_release: "{{ kind_release_tag }}"

        - name: Debug Kind image release
          ansible.builtin.debug:
            msg: "Using kind release '{{ kind_release_tag }}', image 'kindest/node:{{ kind_image_tag }}'"

        - name: Stat Kind executable
          ansible.builtin.stat:
            path: "{{ _kind_bin }}"
          register: kind_bin_file

        - name: Download Kind executable
          ansible.builtin.get_url:
            url: "https://kind.sigs.k8s.io/dl/{{ kind_release }}/kind-{{ kind_release_family }}-{{ kind_release_architecture }}"
            dest: "{{ _kind_bin }}"
            mode: 0777
          when: not (kind_bin_file.stat.exists | bool)
          changed_when: false

    - name: List Kind clusters
      ansible.builtin.command: >-
        {{ _kind_bin }} get clusters -q
      register: kind_cluster_query
      changed_when: false

    - name: Check Kind cluster state
      ansible.builtin.assert:
        that: kind_cluster_name in kind_cluster_query.stdout_lines
        fail_msg: "kind cluster {{ kind_cluster_name }} not found"

    - name: List cluster nodes
      ansible.builtin.shell: >-
        KUBECONFIG={{ kind_kubeconfig }} kubectl get nodes --no-headers
      register: kind_node_query

    - name: Verify Kubectl node query execution
      ansible.builtin.assert:
        that: kind_node_query is succeeded
        fail_msg: "kubectl call to cluster failed"

    - name: Check Kind node
      ansible.builtin.assert:
        that: (kind_node_num | int) == (kind_target_nodes | int)
        fail_msg: "expected {{ kind_target_nodes }} cluster nodes, got {{ kind_node_num }}"
      vars:
        kind_target_nodes: "{{ kind_nodes }}"
        kind_node_num: "{{ kind_node_query.stdout_lines | length }}"

    - name: Deploy Kind image to local repository
      when: kind_registry_deploy | bool
      block:
        - name: Pull Kind image
          community.docker.docker_image:
            name: "kindest/node:{{ lookup('ansible.builtin.env', 'KIND_IMAGE') }}"
            source: pull

        - name: Tag and push to local registry
          community.docker.docker_image:
            name: kindest/node
            repository: "{{ kind_registry_hostname | default('localhost') }}:{{ kind_registry_port }}/kindest/node"
            tag: "{{ lookup('ansible.builtin.env', 'KIND_IMAGE') }}"
            push: true
            source: local
