---
kind_release_tag: "{{ lookup('ansible.builtin.env', 'KIND_RELEASE', default='latest') }}"
kind_image_tag: "{{ lookup('ansible.builtin.env', 'KIND_IMAGE', default='latest') }}"
kind_cluster_state: 'present'
kind_cluster_name: 'kind'
kind_kubeconfig: '~/.kube/config'
kind_multinode: true
kind_network_name: kind
kind_network_addr: 172.60.0.0/16
kind_registry_deploy: true
kind_registry_container: "{{ kind_cluster_name }}-registry"
kind_registry_hostname: "{{ kind_registry_container }}"
kind_registry_port: 5000
kind_registry_cleanup: true
kind_proxy_deploy: true
kind_proxy_container: "{{ kind_cluster_name }}-proxy"
kind_proxy_hostname: "localhost"
kind_proxy_cleanup: true
