---
kind_release_download: false
kind_release_tag: "{{ lookup('ansible.builtin.env', 'KIND_RELEASE', default='latest') }}"
kind_image_tag: "{{ lookup('ansible.builtin.env', 'KIND_IMAGE', default='latest') }}"
kind_cluster_state: 'present'
kind_cluster_name: 'kind'
kind_kubeconfig: '~/.kube/config'
kind_multinode: true
kind_network_name: kind
kind_network_addr: 172.19.0.0/16
kind_registry_deploy: true
kind_registry_container: "{{ kind_cluster_name }}-registry"
kind_registry_hostname: "localhost"
kind_registry_port: 49153
kind_registry_cleanup: true
kind_proxy_deploy: true
kind_proxy_container: "{{ kind_cluster_name }}-proxy"
kind_proxy_hostname: "{{ kind_proxy_container }}"
kind_proxy_cleanup: true
kind_nodes: 4
kind_release_family: "{{ (ansible_system | default('linux') | lower) }}"
kind_architecture: "{{ ansible_architecture | default('x86_64') }}"
kind_release_architecture: "{{ (kind_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}"
