---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: localhost
driver:
  name: delegated
provisioner:
  name: ansible
  playbooks:
    converge: ../common/converge.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
    prepare: ../common/prepare.yml
    cleanup: ../common/cleanup.yml
  inventory:
    hosts:
      all:
        vars:
          ansible_connection: local
          ansible_python_interpreter: python
          _tmpdir: ${MOLECULE_EPHEMERAL_DIRECTORY}
          kind_kubeconfig: ${MOLECULE_EPHEMERAL_DIRECTORY}/config
          kind_cluster_name: molecule-kind
          kind_multinode: true
          kind_registry_hostname: kind-registry
          kind_proxy_hostname: kind-proxy
verifier:
  name: ansible
