---
name: molecule

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: "nephelaiio.kind"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
          - singlenode
          - registry
        k8s:
          - v1.32.2
          - v1.31.6
          - v1.30.10
          - v1.29.14
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.kind"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: "nephelaiio.kind"

      - name: Install dependencies
        run: devbox run -- make install
        working-directory: "nephelaiio.kind"

      - name: Run molecule tests
        run: devbox run -- make test
        working-directory: "nephelaiio.kind"
        env:
          K8S_RELEASE: ${{ matrix.k8s }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
