---
name: release

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: "nephelaiio.kind"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.kind"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: "nephelaiio.kind"

      - name: Release collection
        run: devbox run -- make publish
        env:
          GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
